// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP-pLqpM5Jjt3iYvJuZw6hwIs2BfwYpPY',
    appId: '1:831122608682:web:e62ec166a1308499502953',
    messagingSenderId: '831122608682',
    projectId: 'kissan-connect-3a3ea',
    authDomain: 'kissan-connect-3a3ea.firebaseapp.com',
    databaseURL: 'https://kissan-connect-3a3ea-default-rtdb.firebaseio.com',
    storageBucket: 'kissan-connect-3a3ea.firebasestorage.app',
    measurementId: 'G-0S2385DD9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJF0fOwcDz-imZ0U-_HE8H5_9oI60ux24',
    appId: '1:831122608682:android:e76c3f0e897f5653502953',
    messagingSenderId: '831122608682',
    projectId: 'kissan-connect-3a3ea',
    databaseURL: 'https://kissan-connect-3a3ea-default-rtdb.firebaseio.com',
    storageBucket: 'kissan-connect-3a3ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKpV-gnLW3Rfe6k26rYbKqgAqYX6E9JPQ',
    appId: '1:831122608682:ios:986edbc4ceaf0f10502953',
    messagingSenderId: '831122608682',
    projectId: 'kissan-connect-3a3ea',
    databaseURL: 'https://kissan-connect-3a3ea-default-rtdb.firebaseio.com',
    storageBucket: 'kissan-connect-3a3ea.firebasestorage.app',
    iosBundleId: 'com.example.kissanConnectApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKpV-gnLW3Rfe6k26rYbKqgAqYX6E9JPQ',
    appId: '1:831122608682:ios:986edbc4ceaf0f10502953',
    messagingSenderId: '831122608682',
    projectId: 'kissan-connect-3a3ea',
    databaseURL: 'https://kissan-connect-3a3ea-default-rtdb.firebaseio.com',
    storageBucket: 'kissan-connect-3a3ea.firebasestorage.app',
    iosBundleId: 'com.example.kissanConnectApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP-pLqpM5Jjt3iYvJuZw6hwIs2BfwYpPY',
    appId: '1:831122608682:web:a4f77c5708641cad502953',
    messagingSenderId: '831122608682',
    projectId: 'kissan-connect-3a3ea',
    authDomain: 'kissan-connect-3a3ea.firebaseapp.com',
    databaseURL: 'https://kissan-connect-3a3ea-default-rtdb.firebaseio.com',
    storageBucket: 'kissan-connect-3a3ea.firebasestorage.app',
    measurementId: 'G-FELSQYLXK6',
  );
}
